all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
all_joints_names:
- Client_Mouth
- Client_Eye_L
- Client_Eye_R
- Client_FinBase_L
- Client_FinTip_L
- Client_FinBase_R
- Client_FinTip_R
- Client_Spine_1
- Client_Spine_2
- Client_Tail
- Client_TailTip
- Cleaner_Mouth
- Cleaner_Spine1
- Cleaner_Spine2
- Cleaner_Tail
alpha_r: 0.02
apply_prob: 0.5
batch_size: 8
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets\iteration-3\UnaugmentedDataSet_Top_view_trackingAug19\Top_view_tracking_raul95shuffle3.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
global_scale: 0.8
init_weights: C:\Users\Public\new\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets\iteration-3\UnaugmentedDataSet_Top_view_trackingAug19\Documentation_data-Top_view_tracking_95shuffle3.pickle
min_input_size: 64
mirror: false
multi_stage: true
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_idchannel: 0
num_joints: 15
num_limbs: 55
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 0
  - 4
- - 0
  - 5
- - 0
  - 6
- - 0
  - 7
- - 0
  - 8
- - 0
  - 9
- - 0
  - 10
- - 1
  - 2
- - 1
  - 3
- - 1
  - 4
- - 1
  - 5
- - 1
  - 6
- - 1
  - 7
- - 1
  - 8
- - 1
  - 9
- - 1
  - 10
- - 2
  - 3
- - 2
  - 4
- - 2
  - 5
- - 2
  - 6
- - 2
  - 7
- - 2
  - 8
- - 2
  - 9
- - 2
  - 10
- - 3
  - 4
- - 3
  - 5
- - 3
  - 6
- - 3
  - 7
- - 3
  - 8
- - 3
  - 9
- - 3
  - 10
- - 4
  - 5
- - 4
  - 6
- - 4
  - 7
- - 4
  - 8
- - 4
  - 9
- - 4
  - 10
- - 5
  - 6
- - 5
  - 7
- - 5
  - 8
- - 5
  - 9
- - 5
  - 10
- - 6
  - 7
- - 6
  - 8
- - 6
  - 9
- - 6
  - 10
- - 7
  - 8
- - 7
  - 9
- - 7
  - 10
- - 8
  - 9
- - 8
  - 10
- - 9
  - 10
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: C:\Users\BEE Team\Desktop\Videos DLC\Top_view_tracking-raul-2023-08-19
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false
